seven_tag_variable:
    types:
        url:
            name: 'Url'
            collectorName: 'url'
            helper: 'To configure you need to set one of property of this object like hash or protocol'
        cookie:
            name: 'Cookie'
            collectorName: 'cookie'
            helper: 'To configure you need to put cookie name and as a value you will have value of that cookie'
        document:
            name: 'Document'
            collectorName: 'document'
            helper: 'To configure you need to set one of property of this object like referrer'
        dataLayer:
            name: 'Data Layer'
            collectorName: 'dataLayer'
            helper: 'To configure you need to set name of dataLayer event property'
        constant:
            name: 'Constant'
            collectorName: 'constant'
            helper: 'To configure you need to write value of your constant for example unique id of application'
        random:
            name: 'Random Number'
            collectorName: 'random'
            helper: 'When set it will always return random number as value of variable'
    variables:
        pageUrl:
            name: 'Page Url'
            type: 'url'
            value: 'href'
        campaign:
            name: 'Campaign'
            type: 'url'
            value: 'utm_campaign'
        referrer:
            name: 'Referrer'
            type: 'document'
            value: 'referrer'
        path:
             name: 'Page Path'
             type: 'url'
             value: 'hostname'
        hostname:
             name: 'Page Hostname'
             type: 'url'
             value: 'hostname'
        clickClasses:
             name: 'Click Classes'
             type: 'dataLayer'
             value: 'elementClasses'
        clickId:
             name: 'Click ID'
             type: 'dataLayer'
             value: 'elementId'
        clickUrl:
             name: 'Click Url'
             type: 'dataLayer'
             value: 'elementUrl'
        formId:
             name: 'Form ID'
             type: 'dataLayer'
             value: 'elementId'
        formClasses:
             name: 'Form Classes'
             type: 'dataLayer'
             value: 'elementClasses'
        formUrl:
             name: 'Form Url'
             type: 'dataLayer'
             value: 'elementClasses'
        event:
             name: 'Event'
             type: 'dataLayer'
             value: 'event'