SevenTag\Component\Tag\Model\Tag:
  exclusion_policy: None
  virtual_properties:
    getContainerAccessId:
      serialized_name: container
      type: integer
      groups: [tag]
  accessor_order: custom
  custom_accessor_order: [accessId, name, code, triggers, container, createdAt, updatedAt, documentWrite, disableInDebugMode, isActive, template, templateOptions]
  properties:
    accessId:
      expose: true
      serialized_name: id
      type: integer
      groups: [tags, tag]
    name:
      expose: true
      groups: [tags, tag]
    code:
      expose: true
      groups: [tags, tag]
    priority:
      expose: true
      groups: [tags, tag]
    triggers:
      expose: true
      groups: [triggers]
    createdAt:
      expose: true
      groups: [tags, tag]
    updatedAt:
      expose: true
      groups: [tags, tag]
    documentWrite:
      expose: true
      groups: [tag]
    disableInDebugMode:
      expose: true
      groups: [tag]
    respectVisitorsPrivacy:
      expose: true
      groups: [tag]
    isSynchronous:
      expose: true
      groups: [tag]
    isActive:
      expose: true
      groups: [tags, tag]
    template:
      expose: true
      groups: [tag]
    templateOptions:
      expose: true
      groups: [tag]
