NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

SevenTagTriggerBundle:
    resource: "@SevenTagTriggerBundle/Resources/config/routing.yml"

SevenTagContainerBundle:
    resource: "@SevenTagContainerBundle/Resources/config/routing.yml"
    prefix:   /api

SevenTagUserBundle:
    resource: "@SevenTagUserBundle/Resources/config/routing.yml"
    prefix:   /api

SevenTagTagBundle:
    resource: "@SevenTagTagBundle/Resources/config/routing.yml"
    prefix:   /api

SevenTagSecurityBundle:
    resource: "@SevenTagSecurityBundle/Resources/config/routing.yml"
    prefix:    /api

SevenTagVariableBundle:
    resource: "@SevenTagVariableBundle/Resources/config/routing.yml"
    prefix:   /api

SevenTagAppBundle:
    resource: "@SevenTagAppBundle/Resources/config/routing.yml"
    prefix:    /admin-tools

fos_oauth_server_token:
    path:      /api/oauth/v2/token
    defaults:  { _controller: fos_oauth_server.controller.token:tokenAction }
    requirements:
      _method: POST

fos_reset_password:
    path:      /reset/{token}
    defaults:  { _controller: FOSUserBundle:Resetting:reset }

fos_oauth_server_authorize:
    path:      /api/oauth/v2/auth
    defaults:  { _controller: FOSOAuthServerBundle:Authorize:authorize }
    requirements:
      _method: POST

containers_library:
    resource: "@SevenTagContainerBundle/Controller/ContainersLibraryController.php"
    type:     annotation

containers_privacy:
    resource: "@SevenTagContainerBundle/Controller/ContainersPrivacyController.php"
    type:     annotation

containers_no_script:
    resource: "@SevenTagContainerBundle/Controller/ContainersNoScriptController.php"
    type:     annotation

translations:
    resource: "@SevenTagAppBundle/Controller/TranslationsController.php"
    prefix: /api
    type: rest
