imports:
    - { resource: 'repositories.yml' }
    - { resource: 'forms.yml' }

services:
    seven_tag_tag.template_holder:
      class: SevenTag\Api\TagBundle\Template\Holder

    seven_tag_tag.validator.tag_template_validator:
        class: SevenTag\Api\TagBundle\Validator\Constraints\TagTemplateValidator
        arguments: [@seven_tag_tag.template_holder]
        tags:
            - { name: validator.constraint_validator, alias: seven_tag_tag_template_validator }

    seven_tag_tag.subscriber.tag_template_code_resolver_subscriber:
        class: SevenTag\Api\TagBundle\Listener\TagTemplateCodeResolverSubscriber
        arguments: [@seven_tag_tag.template_holder]
        tags:
            - { name: doctrine.event_subscriber }

    seven_tag_tag.templating_provider:
        class: SevenTag\Api\TagBundle\Template\TemplatingProvider
        public: false
        abstract: true
        calls:
          - [setContainer, [@service_container]]