services:
    seven_tag_container.no_script_crawler:
        class: SevenTag\Api\ContainerBundle\NoScript\NoScriptCrawler

    seven_tag_container.no_script_interceptor:
        class: SevenTag\Api\ContainerBundle\NoScript\DefaultNoScriptInterceptor
        arguments: [@seven_tag_container.no_script_crawler]

    seven_tag_container.no_script_filesystem_subscriber:
      class: SevenTag\Api\ContainerBundle\NoScript\Subscriber\NoScriptsFilesystemSubscriber
      arguments: [@seven_tag_container.no_script_interceptor, @gaufrette.container_library]
      tags:
        - { name: kernel.event_subscriber }