SevenTag\Component\Trigger\Model\Trigger:
  exclusion_policy: all
  virtual_properties:
    getContainerAccessId:
      serialized_name: container
      type: integer
      groups: [trigger, triggers]
    getTagsCount:
      serialized_name: tags_count
      type: integer
      groups: [triggers]
  accessor_order: custom
  custom_accessor_order: [accessId, name, strategy, type, createdAt, updatedAt, conditions, tags_count, container]
  properties:
    accessId:
      expose: true
      serialized_name: id
      type: integer
      groups: [trigger, triggers]
    name:
      expose: true
      groups: [trigger, triggers]
    strategy:
      expose: true
      groups: [trigger, triggers]
    type:
      expose: true
      groups: [trigger, triggers]
    conditions:
      expose: true
      groups: [conditions]
    createdAt:
      expose: true
      groups: [trigger, triggers]
    updatedAt:
      expose: true
      groups: [trigger, triggers]
    isAddedToSynchronousTag:
      expose: true
      groups: [trigger, triggers]
